
let cc = [
    { "area_id": "1", "name": "全国" },
    { "area_id": "33", "name": "嘉峪关市" },
    { "area_id": "34", "name": "金昌市" },
    { "area_id": "35", "name": "白银市" },
    { "area_id": "36", "name": "兰州市" },
    { "area_id": "37", "name": "酒泉市" },
    { "area_id": "38", "name": "大兴安岭地区" },
    { "area_id": "39", "name": "黑河市" },
    { "area_id": "40", "name": "伊春市" },
    { "area_id": "41", "name": "齐齐哈尔市" },
    { "area_id": "42", "name": "佳木斯市" },
    { "area_id": "43", "name": "鹤岗市" },
    { "area_id": "44", "name": "绥化市" },
    { "area_id": "45", "name": "双鸭山市" },
    { "area_id": "46", "name": "鸡西市" },
    { "area_id": "47", "name": "七台河市" },
    { "area_id": "48", "name": "哈尔滨市" },
    { "area_id": "49", "name": "牡丹江市" },
    { "area_id": "50", "name": "大庆市" },
    { "area_id": "51", "name": "白城市" },
    { "area_id": "52", "name": "松原市" },
    { "area_id": "53", "name": "长春市" },
    { "area_id": "54", "name": "延边朝鲜族自治州" },
    { "area_id": "55", "name": "吉林市" },
    { "area_id": "56", "name": "四平市" },
    { "area_id": "57", "name": "白山市" },
    { "area_id": "58", "name": "沈阳市" },
    { "area_id": "59", "name": "阜新市" },
    { "area_id": "60", "name": "铁岭市" },
    { "area_id": "61", "name": "呼伦贝尔市" },
    { "area_id": "62", "name": "兴安盟" },
    { "area_id": "63", "name": "锡林郭勒盟" },
    { "area_id": "64", "name": "通辽市" },
    { "area_id": "65", "name": "海西蒙古族藏族自治州" },
    { "area_id": "66", "name": "西宁市" },
    { "area_id": "67", "name": "海北藏族自治州" },
    { "area_id": "68", "name": "海南藏族自治州" },
    { "area_id": "69", "name": "海东地区" },
    { "area_id": "70", "name": "黄南藏族自治州" },
    { "area_id": "71", "name": "玉树藏族自治州" },
    { "area_id": "72", "name": "果洛藏族自治州" },
    { "area_id": "73", "name": "甘孜藏族自治州" },
    { "area_id": "74", "name": "德阳市" },
    { "area_id": "75", "name": "成都市" },
    { "area_id": "76", "name": "雅安市" },
    { "area_id": "77", "name": "眉山市" },
    { "area_id": "78", "name": "自贡市" },
    { "area_id": "79", "name": "乐山市" },
    { "area_id": "80", "name": "凉山彝族自治州" },
    { "area_id": "81", "name": "攀枝花市" },
    { "area_id": "82", "name": "和田地区" },
    { "area_id": "83", "name": "喀什地区" },
    { "area_id": "84", "name": "克孜勒苏柯尔克孜自治州" },
    { "area_id": "85", "name": "阿克苏地区" },
    { "area_id": "86", "name": "巴音郭楞蒙古自治州" },
    { "area_id": "88", "name": "博尔塔拉蒙古自治州" },
    { "area_id": "89", "name": "吐鲁番地区" },
    { "area_id": "90", "name": "伊犁哈萨克自治州" },
    { "area_id": "91", "name": "哈密地区" },
    { "area_id": "92", "name": "乌鲁木齐市" },
    { "area_id": "93", "name": "昌吉回族自治州" },
    { "area_id": "94", "name": "塔城地区" },
    { "area_id": "95", "name": "克拉玛依市" },
    { "area_id": "96", "name": "阿勒泰地区" },
    { "area_id": "97", "name": "山南地区" },
    { "area_id": "98", "name": "林芝地区" },
    { "area_id": "99", "name": "昌都地区" },
    { "area_id": "100", "name": "拉萨市" },
    { "area_id": "101", "name": "那曲地区" },
    { "area_id": "102", "name": "日喀则地区" },
    { "area_id": "103", "name": "阿里地区" },
    { "area_id": "104", "name": "昆明市" },
    { "area_id": "105", "name": "楚雄彝族自治州" },
    { "area_id": "106", "name": "玉溪市" },
    { "area_id": "107", "name": "红河哈尼族彝族自治州" },
    { "area_id": "108", "name": "普洱市" },
    { "area_id": "109", "name": "西双版纳傣族自治州" },
    { "area_id": "110", "name": "临沧市" },
    { "area_id": "111", "name": "大理白族自治州" },
    { "area_id": "112", "name": "保山市" },
    { "area_id": "113", "name": "怒江傈僳族自治州" },
    { "area_id": "114", "name": "丽江市" },
    { "area_id": "115", "name": "迪庆藏族自治州" },
    { "area_id": "116", "name": "德宏傣族景颇族自治州" },
    { "area_id": "117", "name": "张掖市" },
    { "area_id": "118", "name": "武威市" },
    { "area_id": "119", "name": "东莞市" },
    { "area_id": "120", "name": "东沙群岛" },
    { "area_id": "121", "name": "三亚市" },
    { "area_id": "122", "name": "鄂州市" },
    { "area_id": "123", "name": "乌海市" },
    { "area_id": "124", "name": "莱芜市" },
    { "area_id": "125", "name": "海口市" },
    { "area_id": "126", "name": "蚌埠市" },
    { "area_id": "127", "name": "合肥市" },
    { "area_id": "128", "name": "阜阳市" },
    { "area_id": "129", "name": "芜湖市" },
    { "area_id": "130", "name": "安庆市" },
    { "area_id": "131", "name": "北京市" },
    { "area_id": "132", "name": "重庆市" },
    { "area_id": "133", "name": "南平市" },
    { "area_id": "134", "name": "泉州市" },
    { "area_id": "135", "name": "庆阳市" },
    { "area_id": "136", "name": "定西市" },
    { "area_id": "137", "name": "韶关市" },
    { "area_id": "138", "name": "佛山市" },
    { "area_id": "139", "name": "茂名市" },
    { "area_id": "140", "name": "珠海市" },
    { "area_id": "141", "name": "梅州市" },
    { "area_id": "142", "name": "桂林市" },
    { "area_id": "143", "name": "河池市" },
    { "area_id": "144", "name": "崇左市" },
    { "area_id": "145", "name": "钦州市" },
    { "area_id": "146", "name": "贵阳市" },
    { "area_id": "147", "name": "六盘水市" },
    { "area_id": "148", "name": "秦皇岛市" },
    { "area_id": "149", "name": "沧州市" },
    { "area_id": "150", "name": "石家庄市" },
    { "area_id": "151", "name": "邯郸市" },
    { "area_id": "152", "name": "新乡市" },
    { "area_id": "153", "name": "洛阳市" },
    { "area_id": "154", "name": "商丘市" },
    { "area_id": "155", "name": "许昌市" },
    { "area_id": "156", "name": "襄阳市" },
    { "area_id": "157", "name": "荆州市" },
    { "area_id": "158", "name": "长沙市" },
    { "area_id": "159", "name": "衡阳市" },
    { "area_id": "160", "name": "镇江市" },
    { "area_id": "161", "name": "南通市" },
    { "area_id": "162", "name": "淮安市" },
    { "area_id": "163", "name": "南昌市" },
    { "area_id": "164", "name": "新余市" },
    { "area_id": "165", "name": "通化市" },
    { "area_id": "166", "name": "锦州市" },
    { "area_id": "167", "name": "大连市" },
    { "area_id": "168", "name": "乌兰察布市" },
    { "area_id": "169", "name": "巴彦淖尔市" },
    { "area_id": "170", "name": "渭南市" },
    { "area_id": "171", "name": "宝鸡市" },
    { "area_id": "172", "name": "枣庄市" },
    { "area_id": "173", "name": "日照市" },
    { "area_id": "174", "name": "东营市" },
    { "area_id": "175", "name": "威海市" },
    { "area_id": "176", "name": "太原市" },
    { "area_id": "177", "name": "文山壮族苗族自治州" },
    { "area_id": "178", "name": "温州市" },
    { "area_id": "179", "name": "杭州市" },
    { "area_id": "180", "name": "宁波市" },
    { "area_id": "181", "name": "中卫市" },
    { "area_id": "182", "name": "临夏回族自治州" },
    { "area_id": "183", "name": "辽源市" },
    { "area_id": "184", "name": "抚顺市" },
    { "area_id": "185", "name": "阿坝藏族羌族自治州" },
    { "area_id": "186", "name": "宜宾市" },
    { "area_id": "187", "name": "中山市" },
    { "area_id": "188", "name": "亳州市" },
    { "area_id": "189", "name": "滁州市" },
    { "area_id": "190", "name": "宣城市" },
    { "area_id": "191", "name": "廊坊市" },
    { "area_id": "192", "name": "宁德市" },
    { "area_id": "193", "name": "龙岩市" },
    { "area_id": "194", "name": "厦门市" },
    { "area_id": "195", "name": "莆田市" },
    { "area_id": "196", "name": "天水市" },
    { "area_id": "197", "name": "清远市" },
    { "area_id": "198", "name": "湛江市" },
    { "area_id": "199", "name": "阳江市" },
    { "area_id": "200", "name": "河源市" },
    { "area_id": "201", "name": "潮州市" },
    { "area_id": "202", "name": "来宾市" },
    { "area_id": "203", "name": "百色市" },
    { "area_id": "204", "name": "防城港市" },
    { "area_id": "205", "name": "铜仁地区" },
    { "area_id": "206", "name": "毕节地区" },
    { "area_id": "207", "name": "承德市" },
    { "area_id": "208", "name": "衡水市" },
    { "area_id": "209", "name": "濮阳市" },
    { "area_id": "210", "name": "开封市" },
    { "area_id": "211", "name": "焦作市" },
    { "area_id": "212", "name": "三门峡市" },
    { "area_id": "213", "name": "平顶山市" },
    { "area_id": "214", "name": "信阳市" },
    { "area_id": "215", "name": "鹤壁市" },
    { "area_id": "216", "name": "十堰市" },
    { "area_id": "217", "name": "荆门市" },
    { "area_id": "218", "name": "武汉市" },
    { "area_id": "219", "name": "常德市" },
    { "area_id": "220", "name": "岳阳市" },
    { "area_id": "221", "name": "娄底市" },
    { "area_id": "222", "name": "株洲市" },
    { "area_id": "223", "name": "盐城市" },
    { "area_id": "224", "name": "苏州市" },
    { "area_id": "225", "name": "景德镇市" },
    { "area_id": "226", "name": "抚州市" },
    { "area_id": "227", "name": "本溪市" },
    { "area_id": "228", "name": "盘锦市" },
    { "area_id": "229", "name": "包头市" },
    { "area_id": "230", "name": "阿拉善盟" },
    { "area_id": "231", "name": "榆林市" },
    { "area_id": "232", "name": "铜川市" },
    { "area_id": "233", "name": "西安市" },
    { "area_id": "234", "name": "临沂市" },
    { "area_id": "235", "name": "滨州市" },
    { "area_id": "236", "name": "青岛市" },
    { "area_id": "237", "name": "朔州市" },
    { "area_id": "238", "name": "晋中市" },
    { "area_id": "239", "name": "巴中市" },
    { "area_id": "240", "name": "绵阳市" },
    { "area_id": "241", "name": "广安市" },
    { "area_id": "242", "name": "资阳市" },
    { "area_id": "243", "name": "衢州市" },
    { "area_id": "244", "name": "台州市" },
    { "area_id": "245", "name": "舟山市" },
    { "area_id": "246", "name": "固原市" },
    { "area_id": "247", "name": "甘南藏族自治州" },
    { "area_id": "248", "name": "内江市" },
    { "area_id": "249", "name": "曲靖市" },
    { "area_id": "250", "name": "淮南市" },
    { "area_id": "251", "name": "巢湖市" },
    { "area_id": "252", "name": "黄山市" },
    { "area_id": "253", "name": "淮北市" },
    { "area_id": "254", "name": "三明市" },
    { "area_id": "255", "name": "漳州市" },
    { "area_id": "256", "name": "陇南市" },
    { "area_id": "257", "name": "广州市" },
    { "area_id": "258", "name": "云浮市" },
    { "area_id": "259", "name": "揭阳市" },
    { "area_id": "260", "name": "贺州市" },
    { "area_id": "261", "name": "南宁市" },
    { "area_id": "262", "name": "遵义市" },
    { "area_id": "263", "name": "安顺市" },
    { "area_id": "264", "name": "张家口市" },
    { "area_id": "265", "name": "唐山市" },
    { "area_id": "266", "name": "邢台市" },
    { "area_id": "267", "name": "安阳市" },
    { "area_id": "268", "name": "郑州市" },
    { "area_id": "269", "name": "驻马店市" },
    { "area_id": "270", "name": "宜昌市" },
    { "area_id": "271", "name": "黄冈市" },
    { "area_id": "272", "name": "益阳市" },
    { "area_id": "273", "name": "邵阳市" },
    { "area_id": "274", "name": "湘西土家族苗族自治州" },
    { "area_id": "275", "name": "郴州市" },
    { "area_id": "276", "name": "泰州市" },
    { "area_id": "277", "name": "宿迁市" },
    { "area_id": "278", "name": "宜春市" },
    { "area_id": "279", "name": "鹰潭市" },
    { "area_id": "280", "name": "朝阳市" },
    { "area_id": "281", "name": "营口市" },
    { "area_id": "282", "name": "丹东市" },
    { "area_id": "283", "name": "鄂尔多斯市" },
    { "area_id": "284", "name": "延安市" },
    { "area_id": "285", "name": "商洛市" },
    { "area_id": "286", "name": "济宁市" },
    { "area_id": "287", "name": "潍坊市" },
    { "area_id": "288", "name": "济南市" },
    { "area_id": "289", "name": "上海市" },
    { "area_id": "290", "name": "晋城市" },
    { "area_id": "291", "name": "南充市" },
    { "area_id": "292", "name": "丽水市" },
    { "area_id": "293", "name": "绍兴市" },
    { "area_id": "294", "name": "湖州市" },
    { "area_id": "295", "name": "北海市" },
    { "area_id": "297", "name": "赤峰市" },
    { "area_id": "298", "name": "六安市" },
    { "area_id": "299", "name": "池州市" },
    { "area_id": "300", "name": "福州市" },
    { "area_id": "301", "name": "惠州市" },
    { "area_id": "302", "name": "江门市" },
    { "area_id": "303", "name": "汕头市" },
    { "area_id": "304", "name": "梧州市" },
    { "area_id": "305", "name": "柳州市" },
    { "area_id": "306", "name": "黔南布依族苗族自治州" },
    { "area_id": "307", "name": "保定市" },
    { "area_id": "308", "name": "周口市" },
    { "area_id": "309", "name": "南阳市" },
    { "area_id": "310", "name": "孝感市" },
    { "area_id": "311", "name": "黄石市" },
    { "area_id": "312", "name": "张家界市" },
    { "area_id": "313", "name": "湘潭市" },
    { "area_id": "314", "name": "永州市" },
    { "area_id": "315", "name": "南京市" },
    { "area_id": "316", "name": "徐州市" },
    { "area_id": "317", "name": "无锡市" },
    { "area_id": "318", "name": "吉安市" },
    { "area_id": "319", "name": "葫芦岛市" },
    { "area_id": "320", "name": "鞍山市" },
    { "area_id": "321", "name": "呼和浩特市" },
    { "area_id": "322", "name": "吴忠市" },
    { "area_id": "323", "name": "咸阳市" },
    { "area_id": "324", "name": "安康市" },
    { "area_id": "325", "name": "泰安市" },
    { "area_id": "326", "name": "烟台市" },
    { "area_id": "327", "name": "吕梁市" },
    { "area_id": "328", "name": "运城市" },
    { "area_id": "329", "name": "广元市" },
    { "area_id": "330", "name": "遂宁市" },
    { "area_id": "331", "name": "泸州市" },
    { "area_id": "332", "name": "天津市" },
    { "area_id": "333", "name": "金华市" },
    { "area_id": "334", "name": "嘉兴市" },
    { "area_id": "335", "name": "石嘴山市" },
    { "area_id": "336", "name": "昭通市" },
    { "area_id": "337", "name": "铜陵市" },
    { "area_id": "338", "name": "肇庆市" },
    { "area_id": "339", "name": "汕尾市" },
    { "area_id": "340", "name": "深圳市" },
    { "area_id": "341", "name": "贵港市" },
    { "area_id": "342", "name": "黔东南苗族侗族自治州" },
    { "area_id": "343", "name": "黔西南布依族苗族自治州" },
    { "area_id": "344", "name": "漯河市" },
    { "area_id": "346", "name": "扬州市" },
    { "area_id": "347", "name": "连云港市" },
    { "area_id": "348", "name": "常州市" },
    { "area_id": "349", "name": "九江市" },
    { "area_id": "350", "name": "萍乡市" },
    { "area_id": "351", "name": "辽阳市" },
    { "area_id": "352", "name": "汉中市" },
    { "area_id": "353", "name": "菏泽市" },
    { "area_id": "354", "name": "淄博市" },
    { "area_id": "355", "name": "大同市" },
    { "area_id": "356", "name": "长治市" },
    { "area_id": "357", "name": "阳泉市" },
    { "area_id": "358", "name": "马鞍山市" },
    { "area_id": "359", "name": "平凉市" },
    { "area_id": "360", "name": "银川市" },
    { "area_id": "361", "name": "玉林市" },
    { "area_id": "362", "name": "咸宁市" },
    { "area_id": "363", "name": "怀化市" },
    { "area_id": "364", "name": "上饶市" },
    { "area_id": "365", "name": "赣州市" },
    { "area_id": "366", "name": "聊城市" },
    { "area_id": "367", "name": "忻州市" },
    { "area_id": "368", "name": "临汾市" },
    { "area_id": "369", "name": "达州市" },
    { "area_id": "370", "name": "宿州市" },
    { "area_id": "371", "name": "随州市" },
    { "area_id": "372", "name": "德州市" },
    { "area_id": "373", "name": "恩施土家族苗族自治州" },
    { "area_id": "731", "name": "阿拉尔市" },
    { "area_id": "770", "name": "石河子市" },
    { "area_id": "789", "name": "五家渠市" },
    { "area_id": "792", "name": "图木舒克市" },
    { "area_id": "1214", "name": "定安县" },
    { "area_id": "1215", "name": "儋州市" },
    { "area_id": "1216", "name": "万宁市" },
    { "area_id": "1217", "name": "保亭黎族苗族自治县" },
    { "area_id": "1218", "name": "西沙群岛" },
    { "area_id": "1277", "name": "济源市" },
    { "area_id": "1293", "name": "潜江市" },
    { "area_id": "1498", "name": "中沙群岛" },
    { "area_id": "1515", "name": "南沙群岛" },
    { "area_id": "1641", "name": "屯昌县" },
    { "area_id": "1642", "name": "昌江黎族自治县" },
    { "area_id": "1643", "name": "陵水黎族自治县" },
    { "area_id": "1644", "name": "五指山市" },
    { "area_id": "1713", "name": "仙桃市" },
    { "area_id": "2031", "name": "琼中黎族苗族自治县" },
    { "area_id": "2032", "name": "乐东黎族自治县" },
    { "area_id": "2033", "name": "临高县" },
    { "area_id": "2358", "name": "琼海市" },
    { "area_id": "2359", "name": "白沙黎族自治县" },
    { "area_id": "2634", "name": "东方市" },
    { "area_id": "2654", "name": "天门市" },
    { "area_id": "2734", "name": "神农架林区" },
    { "area_id": "2757", "name": "澄迈县" },
    { "area_id": "2758", "name": "文昌市" },
    { "area_id": "2911", "name": "澳门特别行政区" },
    { "area_id": "2912", "name": "香港特别行政区" },
    { "area_id": "9001", "name": "桃园市" },
    { "area_id": "9002", "name": "台北市" },
    { "area_id": "9003", "name": "南投县" },
    { "area_id": "9004", "name": "嘉义市" },
    { "area_id": "9005", "name": "彰化县" },
    { "area_id": "9006", "name": "新竹县" },
    { "area_id": "9007", "name": "澎湖县" },
    { "area_id": "9008", "name": "台东县" },
    { "area_id": "9009", "name": "宜兰县" },
    { "area_id": "9010", "name": "新北市" },
    { "area_id": "9011", "name": "基隆市" },
    { "area_id": "9012", "name": "屏东县" },
    { "area_id": "9013", "name": "嘉义县" },
    { "area_id": "9014", "name": "云林县" },
    { "area_id": "9015", "name": "花莲县" },
    { "area_id": "9016", "name": "台南市" },
    { "area_id": "9017", "name": "台中市" },
    { "area_id": "9018", "name": "新竹市" },
    { "area_id": "9019", "name": "高雄市" },
    { "area_id": "9020", "name": "苗栗县" }
];

/**
 * @exports ZBdCityCodeUtil
 * @classdesc 全国行政区划名称与代号工具类。此类为Object实例，不需要new
 * @class
 */
let ZBdCityCodeUtil = {

    /**
     * 获取城市数组
     * @return {Array}
     */
    getCityCodes: function () {
        return cc;
    },

    /**
     * 获取城市编码
     * @param {String} name 城市名称
     * @return {String}
     */
    getCityCodeByName: function (name) {
        for (let i = 0, len = cc.length; i < len; i++) {
            if (cc[i].name === name) {
                return cc[i].area_id;
            }
        }
        return null;
    },

    /**
     * 获取城市名称
     * @param {String} code 城市编码
     * @return {String}
     */
    getCityNameByCode: function (code) {
        for (let i = 0, len = cc.length; i < len; i++) {
            if (cc[i].area_id === code) {
                return cc[i].name;
            }
        }
        return null;
    }
};

export default ZBdCityCodeUtil;